### ISSUE TITLE
Question: Is there a way to disable line wrapping?

### ISSUE THREAD

**Issue by hub-stuff** [MoaidHathot/Dumpify#3] opened 2023-05-31 16:10 UTC
In case there is much to dump on a single line I saw values being continued in next line. It would be good to be able to allow that all stuff is rendered to one line only. Below image shows the issue
![image](https://github.com/MoaidHathot/Dumpify/assets/135149679/ffb1e79c-1de6-4ca0-9e7f-0ecc5c82a8e5)

**Comment by MoaidHathot** [comment] 2023-05-31 22:23
Hi @hub-stuff, thanks for the suggestion. 
I have a follow up question: Does this happen when the rendered table-width is almost equals to your terminal's width?

**Comment by hub-stuff** [comment] 2023-06-01 08:12
This happens when object has more parameters nested - I guess. 
It can get even more wrapped see below (names are a bit altered but number of chars are the same). 
I am using value.DumpText(members: new MembersConfig { IncludeNonPublicMembers = true });

![image](https://github.com/MoaidHathot/Dumpify/assets/135149679/c8646b0a-8344-45d0-9475-2662466b6fec)

**Comment by MoaidHathot** [comment] 2023-06-01 11:29
Oh, I see, you are correct- when using `DumpText` the rendered table's width should not be limited and the lines should not be wrapped by default.
I will take a look into this and update. Thanks @hub-stuff

**Comment by MoaidHathot** [comment] 2023-07-11 19:57
Reopening the issue due to a bug

**Comment by tcortega** [comment] 2023-07-11 20:27
> Unfortunately, this change alone is not enough. https://github.com/MoaidHathot/Dumpify/issues/3 isn't fully resolved, and in some cases this change can produce a new bug when NoWrapping is enabled but there is not enough place to output the Table, therefore ... is outputted instead.
In order for https://github.com/MoaidHathot/Dumpify/issues/3 to be resolved, we should use a custom IAnsiConsoleOutput and specify big enough Width/Height values, since the defaults are DefaultTerminalWidth which are very small (80 pixels).

This seems to be more of a Spectre.Console problem, look at this issue:
https://github.com/spectreconsole/spectre.console/issues/1185

**Comment by MoaidHathot** [comment] 2023-07-11 20:54
That might be the Root cause, and we should monitor the issue in Specture.Console regarding the wrapping. In the meanwhile, the workaround I suggested with the custom `IAnsiConsoleOutput` works and is very simple to implement. We just need to think of a proper way to determine when to change the default `IAnsiConsoleOutput` and use the custom one instead.

Something like 
```csharp
internal class LargeConsoleSizeOutput : IAnsiConsoleOutput
{
    public LargeConsoleSizeOutput(TextWriter writer)
        => Writer = writer;

    public void SetEncoding(Encoding encoding)
        => System.Console.OutputEncoding = encoding;

    public TextWriter Writer { get; }
    public bool IsTerminal => false;
    public int Width => 1000;
    public int Height => 1000;
}
```

Then in `SpectreConsoleRenderedObject` use
```csharp
 public void Output(IDumpOutput output)
    {
        var console = AnsiConsole.Create(new AnsiConsoleSettings
        {
            Ansi = AnsiSupport.No,
            ColorSystem = ColorSystemSupport.Detect,
            //Out = new AnsiConsoleOutput(output.TextWriter),
            Out = new LargeConsoleSizeOutput(output.TextWriter),
        });

        console.Write(_renderable);
        console.WriteLine();
    }
```

**Comment by tcortega** [comment] 2023-07-11 20:56
> That might be the Root cause, and we should monitor the issue in Specture.Console regarding the wrapping. In the meanwhile, the workaround I suggested with the custom `IAnsiConsoleOutput` works and is very simple to implement. We just need to think of a proper way to determine when to change the default `IAnsiConsoleOutput` and use the custom one instead.
> 
> Something like
> 
> ```cs
> internal class LargeConsoleSizeOutput : IAnsiConsoleOutput
> {
>     public LargeConsoleSizeOutput(TextWriter writer)
>         => Writer = writer;
> 
>     public void SetEncoding(Encoding encoding)
>         => System.Console.OutputEncoding = encoding;
> 
>     public TextWriter Writer { get; }
>     public bool IsTerminal => false;
>     public int Width => 1000;
>     public int Height => 1000;
> }
> ```
> 
> Then in `SpectreConsoleRenderedObject` use
> 
> ```cs
>  public void Output(IDumpOutput output)
>     {
>         var console = AnsiConsole.Create(new AnsiConsoleSettings
>         {
>             Ansi = AnsiSupport.No,
>             ColorSystem = ColorSystemSupport.Detect,
>             //Out = new AnsiConsoleOutput(output.TextWriter),
>             Out = new LargeConsoleSizeOutput(output.TextWriter),
>         });
> 
>         console.Write(_renderable);
>         console.WriteLine();
>     }
> ```

I suppose the best way would be to always use a custom `IAnsiConsoleOutput` and let the user define if he wants to tweak the Width and Height through the `RendererConfig`.

**Comment by MoaidHathot** [comment] 2023-07-11 21:01
@tcortega, we can grant the user this flexibility, but for some APIs, like `DumpText`, we should use larger width/height by default.

**Comment by tcortega** [comment] 2023-07-12 01:10
> @tcortega, we can grant the user this flexibility, but for some APIs, like `DumpText`, we should use larger width/height by default. Which is simple to do, we just need to auto-adjust the `RendererConfig` when `DumpText` is called, if the user did not provide a width/height explicitly.

Regarding to the terminal size, I think that if we're going to have a default terminal size that is too large, it might not be worth keep giving an user the option to print the table as expanded.

It's probably best if we leave things the way they currently work, where Spectre.Console figures out the size of the terminal, but still give an user the choice to override the width whenever he needs it.

Also, I was debugging the problem reported on the issue I linked above, and it seems to be non-related at all to what we're facing. It is specific to the fact that the guy is using a Tree in his tables.

**Comment by MoaidHathot** [comment] 2023-07-13 11:31
@tcortega, we won't change how `Spectre.Console` determines the size of the Terminal, but in `DumpText` there is Terminal, so it makes since IMO to use a large default, since `spectre.Console` uses the smallest size when it can't detect Terminal Rendering, leading to this Issue.
I'm hesitant in keeping `Expanded` and `NoWrap` since they may lead to the issue I was describing before, which is when `Spectre.Console` decide not to render a component because there is not enough space, at least until we have a workaround for that, maybe by rendering a warning instead of the `...` that `Spectre.Console` put there.

**Comment by MoaidHathot** [comment] 2023-07-13 23:05
> @tcortega, we won't change how `Spectre.Console` determines the size of the Terminal, but in `DumpText` there is no Terminal, so it makes since IMO to use a large default, since `spectre.Console` uses the smallest size when it can't detect Terminal Rendering, leading to this Issue. I'm hesitant in keeping `Expanded` and `NoWrap` since they may lead to the issue I was describing before, which is when `Spectre.Console` decide not to render a component because there is not enough space, at least until we have a workaround for that, maybe by rendering a warning instead of the `...` that `Spectre.Console` put there.

This issue is fixed with the following [commit](https://github.com/MoaidHathot/Dumpify/commit/1c5d176adb7548639a033024c9ebc8ca9798e48a) by doing the following:
* The dimensions of the rendered area (width/height) is now configurable
* `DumpText` set a large default for the rendered area's dimensions (users can change it)
* The rendered area dimensions' can be overridden by the user via `OutputConfig`

**Closed** 2023-07-13 23:07 UTC
Labels: enhancement, question

**Comment by MoaidHathot** [comment] 2023-07-18 00:08
@hub-stuff, this is now has been released in [v0.6.0](https://github.com/MoaidHathot/Dumpify/releases/tag/0.6.0).
Thanks @tcortega

**Comment by hub-stuff** [comment] 2023-08-02 08:18
Could you please sign dumpify?
One odmy projects requiee this.

wt., 18 lip 2023, 02:08 użytkownik Moaid Hathot ***@***.***>
napisał:

**Comment by MoaidHathot** [comment] 2023-08-03 22:48
@hub-stuff, sure. I've opened issue #15 to track it. I will look into it, planning to release it this month.
