### ISSUE TITLE
Character encoding problem in PowerShell (rare & intermittent)

### ISSUE THREAD

**Issue by dgilleland** [MoaidHathot/Dumpify#25] opened 2024-02-28 12:44 UTC
I'm "re-using" Dumpify as a way to do a quick'n'dirty representation of a 2D array of `char` values for a BattleShip concept. It's just a temporary usage for a concept presentation. But I've noticed a very rare and unpredictable messing up of the border characters every once in a while when I run my code (even without code changes). Here's what I'm seeing.

![image](https://github.com/MoaidHathot/Dumpify/assets/4458296/0840f02b-60a1-4025-89a4-16182d939623)

When it happens, it's not always those incorrect characters - sometimes it's different ones. Again, this is quite rare and hard to reproduce. The code usage is quite simple (.NET 8 console app, running in PowerShell, on Windows 11):

```csharp
void Concept()
{
    char[,] grid = new char[10,10];
    // Initialize
    for(int row = 0; row < 10; row++)
        for(int col = 0; col < 10; col++)
            grid[row,col] = Random.Shared.Next(10) switch
            {
                < 7 => ' ',
                >= 7 and < 9 => '-',
                _   => Random.Shared.Next(5) switch
                {
                    < 4 => '-',
                    _ => 'H'
                }
            };

    grid.Dump("Player Won");
}
```

**Comment by MoaidHathot** [comment] 2024-02-28 23:41
Hi, thanks for reporting this!
I will try to reproduce it to look further into it, although it is more likely to be a bug in `Spectre.Console`.

**Comment by MoaidHathot** [comment] 2024-03-18 06:54
@dgilleland, I tried running the code in a loop for 5-10 minutes but it didn't reproduce for me. Does it still reproduce for you?

**Comment by MoaidHathot** [comment] 2024-08-24 07:03
Closing since I couldn't reproduce it

**Closed by MoaidHathot** 2024-08-24 07:03 UTC

**Comment by code1line** [comment] 2024-09-17 11:46
The Solution:
`System.Console.OutputEncoding = System.Text.Encoding.UTF8;`
